#! /bin/bash 
# -*- coding: UTF-8 -*-
###########################################################################################
# Script de configuration pour 
#   - la simulation 
#       ModelSim de Mentor Graphics
#   - la synthèse sur Asic avec 
#       Design Vision de Synosys
#   - l'étude de tracé de cellules standards avec CDS IC de Cadence (= Virtuoso)
#   - le placement et le routage sur Asic avec
#       EDI System (= SoC Encounter) de Cadence  
#       le kit technologique (design kit) d'Austria Micro System (AMS)
# –––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––
# Il est attendu que le présent script soit placé dans le sous-répertoire "config" de 
# l'arborescence du TP. La base de l'arborescence du TP est donc le répertoire parent du 
# répertoire contenant ce script. Le chemin complet (absolu) de la base de l'arborescence 
# est déterminé par le script
# /tp/outils/cheminduparent
#
# ATTENTION 
# Pour toujours obtenir le nom d'un script à l'intérieur de celui-ci, qu'il soit exécuté ou 
# sourcé, il convient d'utiliser la variable d'environnement $BASH_SOURCE. En effet, $0 
# retourne le nom de l'interpréteur de commandes utilisé. Le résultat est donc différent
# selon que le script est exécuté ou sourcé.
###########################################################################################

export TP_PATH=$(/tp/outils/cheminduparent $BASH_SOURCE)
printf "\nTP_PATH (base de l'arborescence du TP) = \n%s\n\n" "$TP_PATH"

source /softslin/configCAO/Synopsys/licence_synopsys
source /softslin/configCAO/Synopsys/config_DesignVision

source /softslin/configCAO/Cadence/licence_cadence
source /softslin/configCAO/Cadence/config_Virtuoso
#source /softslin/configCAO/Cadence/config_EDISystem10_10
source /softslin/configCAO/Cadence/config_Innovus_17
source /softslin/configCAO/Cadence/config_QRC
source /softslin/configCAO/AMS/config_AMS_ISR
source /softslin/configCAO/MentorGraphics/config_Calibre
#source /softslin/configCAO/MentorGraphics/config_calibre2015_1_38_27
source /softslin/configCAO/MentorGraphics/licence_mentor_graphics
	# ATTENTION à l'ordre : en interne modelsim.ini utilise des variables définies dans
	# config_ISE et dans config_AMS
source /softslin/configCAO/Xilinx/config_ISE
source /softslin/configCAO/MentorGraphics/config_Questa107c
#source /softslin/configCAO/MentorGraphics/config_modelsim10_4
#source /softslin/configCAO/MentorGraphics/config_ModelSim
export MODELSIM="${TP_PATH}/config/modelsim.ini"

